name = "SymbolicSMT"
uuid = "a0d8a0e1-65bc-4be1-9afb-79a704359442"
authors = ["Shashi Gowda <shashigowda91@gmail.com>"]
version = "1.1.0"

[deps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Z3 = "06b161dc-0161-11ea-0f74-41f836f4024b"

[compat]
SymbolicUtils = "3.32, 4"
Symbolics = "6"
Z3 = "1.0"
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
